for term in 'CHGPEN ' 'CHGTRN ' 'VDW '
do
	grep $term amoebaplusNonbonded.prm  | grep -P ' C(?!l)' 
	grep $term amoebaplusNonbonded.prm  | grep ' r3' 
	grep $term amoebaplusNonbonded.prm  | grep ' r4' 
	grep $term amoebaplusNonbonded.prm  | grep ' r5' 
	grep $term amoebaplusNonbonded.prm  | grep ' r6' 
	grep $term amoebaplusNonbonded.prm  | grep ' r7' 
	grep $term amoebaplusNonbonded.prm  | grep ' H' 
	grep $term amoebaplusNonbonded.prm  | grep ' n-H' 
	grep $term amoebaplusNonbonded.prm  | grep ' i-H' 
	grep $term amoebaplusNonbonded.prm  | grep ' t-H' 
	grep $term amoebaplusNonbonded.prm  | grep ' O' 
	grep $term amoebaplusNonbonded.prm  | grep ' n-O' 
	grep $term amoebaplusNonbonded.prm  | grep ' i-O' 
	grep $term amoebaplusNonbonded.prm  | grep ' N' 
	grep $term amoebaplusNonbonded.prm  | grep ' S' 
	grep $term amoebaplusNonbonded.prm  | grep ' P' 
	grep $term amoebaplusNonbonded.prm  | grep ' F' 
	grep $term amoebaplusNonbonded.prm  | grep ' Cl' 
	grep $term amoebaplusNonbonded.prm  | grep ' Br' 
	grep $term amoebaplusNonbonded.prm  | grep ' I' 
done