import shutil
from rdkit import Chem

# this is to modify the intermediate tinker key files generated by poltype

def modkey2(poltype):
  rdkitmol = Chem.MolFromMolFile(poltype.molstructfname,removeHs=False)
  scaleDipoleAtoms = []
  fixDipoleAtoms = []
  # match acid or ester
  smt = "[C](=O)[O][H,C]" 
  pattern = Chem.MolFromSmarts(smt)
  match = rdkitmol.GetSubstructMatches(pattern)
  #if match:
  #  for i in range(len(match)):	
 
  # scale dipole of two O
  