"""
poltype.output.key_writer – AMOEBA ``.key`` parameter file writer.

Writes an AMOEBA key file that references the base parameter file and
includes atom definitions plus all fitted parameters available in the
pipeline context.

Fitted parameter artifacts consumed
------------------------------------
``multipoles``
    ``list[MultipoleParam]`` – one entry per unique atom type.
``polarization_params``
    ``list[PolarizeParam]`` – one entry per unique atom type.
``torsion_params``
    ``list[TorsionParam]`` – one entry per fitted torsion dihedral.

When a fitted-parameter artifact is absent the corresponding section is
omitted (except for lightweight comment annotations that are written
when ``multipole_frames`` / ``torsion_scans`` metadata artifacts are
present).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List

if TYPE_CHECKING:
    from poltype.pipeline.context import PipelineContext

from poltype.output.params import MultipoleParam, PolarizeParam, TorsionParam
from poltype.output.writer import OutputWriter

logger = logging.getLogger(__name__)


class KeyFileWriter(OutputWriter):
    """Write an AMOEBA ``.key`` parameter file from the pipeline context.

    Parameters
    ----------
    output_dir:
        Directory for the output file.  Falls back to ``context.work_dir``.
    filename:
        Name of the output file.  Defaults to ``"final.key"``.
    """

    def __init__(
        self,
        output_dir: Path | None = None,
        filename: str = "final.key",
    ) -> None:
        super().__init__(output_dir=output_dir)
        self._filename = filename

    @property
    def name(self) -> str:
        return "key_writer"

    def write(self, context: "PipelineContext") -> Path:
        """Write the AMOEBA key file.

        Returns
        -------
        Path
            Absolute path to the written ``final.key``.

        Raises
        ------
        ValueError
            If no molecule is available in the context.
        """
        mol = context.molecule
        if mol is None:
            raise ValueError("No molecule in context; cannot write key file")

        out_dir = self._resolve_dir(context)
        out_path = out_dir / self._filename

        lines = self._build_key_lines(context)
        out_path.write_text("\n".join(lines) + "\n")
        logger.info("Wrote AMOEBA key file: %s", out_path)
        return out_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _fmt_multipole(mp: MultipoleParam) -> List[str]:
        """Format a single :class:`MultipoleParam` as AMOEBA key lines.

        The layout follows the AMOEBA Tinker convention::

            multipole  type  f1 [f2 [f3]]      charge
                                         dx    dy    dz
                                         Qxx
                                         Qyx   Qyy
                                         Qzx   Qzy   Qzz
        """
        frame_str = "  ".join(f"{f:>5d}" for f in mp.frame)
        dx, dy, dz = mp.dipole
        qxx, qyx, qyy, qzx, qzy, qzz = mp.quadrupole
        indent = " " * 33
        return [
            f"multipole  {mp.atom_type:>5d}  {frame_str}  {mp.charge:>14.5f}",
            f"{indent}{dx:>10.5f}  {dy:>10.5f}  {dz:>10.5f}",
            f"{indent}{qxx:>10.5f}",
            f"{indent}{qyx:>10.5f}  {qyy:>10.5f}",
            f"{indent}{qzx:>10.5f}  {qzy:>10.5f}  {qzz:>10.5f}",
        ]

    @staticmethod
    def _fmt_polarize(pp: PolarizeParam) -> str:
        """Format a single :class:`PolarizeParam` as an AMOEBA key line.

        Layout::

            polarize  type   alpha   thole   n1  n2  ...
        """
        neighbor_str = "  ".join(f"{n:>5d}" for n in pp.neighbors)
        base = f"polarize  {pp.atom_type:>5d}  {pp.alpha:>10.4f}  {pp.thole:>8.4f}"
        return f"{base}  {neighbor_str}" if neighbor_str else base

    @staticmethod
    def _fmt_torsion(tp: TorsionParam) -> str:
        """Format a single :class:`TorsionParam` as an AMOEBA key line.

        Layout::

            torsion  a  b  c  d  v1 ph1 n1  v2 ph2 n2  ...
        """
        a, b, c, d = tp.atom_types
        fold_parts = "  ".join(
            f"{f.amplitude:.3f} {f.phase:.1f} {f.periodicity}"
            for f in tp.folds
        )
        return f"torsion  {a:>5d}  {b:>5d}  {c:>5d}  {d:>5d}  {fold_parts}"

    # ------------------------------------------------------------------
    # Core assembly
    # ------------------------------------------------------------------

    def _build_key_lines(self, context: "PipelineContext") -> List[str]:
        """Assemble the key-file content lines."""
        mol = context.molecule
        config = context.config
        lines: List[str] = []

        # ---- Header ----
        lines.append("# AMOEBA key file generated by Poltype2")
        lines.append(f"# Molecule: {mol.name}")
        lines.append(f"# Formula:  {mol.formula}")
        lines.append(f"# Atoms:    {mol.num_atoms}")
        lines.append("")

        # ---- Parameter file reference ----
        lines.append(f"parameters  {config.prm_file_path}")
        lines.append("")

        # ---- Atom definitions ----
        lines.append("# Atom definitions")
        rdmol = mol.rdmol
        type_records = context.get_artifact("type_records")
        for i in range(mol.num_atoms):
            atom = rdmol.GetAtomWithIdx(i)
            symbol = atom.GetSymbol()
            tinker_idx = i + 1
            atomic_num = atom.GetAtomicNum()
            mass = atom.GetMass()
            valence = atom.GetTotalDegree()
            if type_records is not None and i < len(type_records):
                atype = type_records[i].atom_type or tinker_idx
                aclass = type_records[i].atom_class or tinker_idx
                desc = type_records[i].description or f"{mol.name} {symbol}{tinker_idx}"
            else:
                atype = tinker_idx
                aclass = tinker_idx
                desc = f"{mol.name} {symbol}{tinker_idx}"
            lines.append(
                f"atom  {atype:>5d}  {aclass:>5d}  {symbol:<2s}"
                f'  "{desc}"'
                f"  {atomic_num:>5d}  {mass:>10.3f}  {valence:>3d}"
            )
        lines.append("")

        # ---- Optimisation energy (metadata comment) ----
        opt_result = context.get_artifact("opt_result")
        if opt_result is not None:
            lines.append(
                f"# Optimised energy: {opt_result.energy:.6f} Hartree"
            )
            lines.append("")

        # ---- Multipoles ----
        multipoles: list = context.get_artifact("multipoles") or []
        multipole_frames = context.get_artifact("multipole_frames")

        if multipoles:
            lines.append("#")
            lines.append("# Multipoles from Electrostatic Potential Fitting")
            lines.append("#")
            lines.append("")
            for mp in multipoles:
                lines.extend(self._fmt_multipole(mp))
            lines.append("")
        elif multipole_frames is not None:
            # DMA metadata available but fitting not yet done — annotate only.
            lines.append("# Multipole frames from DMA (distributed multipole analysis)")
            lines.append(
                f"# DMA method: {multipole_frames.get('dma_method', 'N/A')}"
                f"  basis: {multipole_frames.get('dma_basis_set', 'N/A')}"
            )
            lines.append("")

        # ---- Polarization ----
        polarization_params: list = context.get_artifact("polarization_params") or []
        if polarization_params:
            lines.append("")
            for pp in polarization_params:
                lines.append(self._fmt_polarize(pp))
            lines.append("")

        # ---- Torsions ----
        torsion_params: list = context.get_artifact("torsion_params") or []
        torsion_scans = context.get_artifact("torsion_scans")

        if torsion_params:
            lines.append("")
            for tp in torsion_params:
                lines.append(self._fmt_torsion(tp))
            lines.append("")
        elif torsion_scans is not None and torsion_scans:
            # Scan data available but fitting not yet done — annotate only.
            lines.append(f"# Torsion scans: {len(torsion_scans)} bond(s)")
            for bond in torsion_scans:
                lines.append(f"#   bond {bond}")
            lines.append("")

        return lines
