"""
poltype.output.key_writer – AMOEBA ``.key`` parameter file writer.

Writes a skeleton AMOEBA key file that references the base parameter
file and includes atom definitions derived from the current molecule.

The full key file (with multipole, torsion, and vdW parameters) will
be produced in later phases once the fitting stages produce those
parameters.  For now the writer outputs a structurally correct file
that Tinker can load.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict

if TYPE_CHECKING:
    from poltype.pipeline.context import PipelineContext

from poltype.output.writer import OutputWriter

logger = logging.getLogger(__name__)


class KeyFileWriter(OutputWriter):
    """Write an AMOEBA ``.key`` parameter file from the pipeline context.

    Parameters
    ----------
    output_dir:
        Directory for the output file.  Falls back to ``context.work_dir``.
    filename:
        Name of the output file.  Defaults to ``"final.key"``.
    """

    def __init__(
        self,
        output_dir: Path | None = None,
        filename: str = "final.key",
    ) -> None:
        super().__init__(output_dir=output_dir)
        self._filename = filename

    @property
    def name(self) -> str:
        return "key_writer"

    def write(self, context: "PipelineContext") -> Path:
        """Write the AMOEBA key file.

        Returns
        -------
        Path
            Absolute path to the written ``final.key``.

        Raises
        ------
        ValueError
            If no molecule is available in the context.
        """
        mol = context.molecule
        if mol is None:
            raise ValueError("No molecule in context; cannot write key file")

        out_dir = self._resolve_dir(context)
        out_path = out_dir / self._filename

        lines = self._build_key_lines(context)
        out_path.write_text("\n".join(lines) + "\n")
        logger.info("Wrote AMOEBA key file: %s", out_path)
        return out_path

    def _build_key_lines(self, context: "PipelineContext") -> list[str]:
        """Assemble the key-file content lines."""
        mol = context.molecule
        config = context.config
        lines: list[str] = []

        # Header
        lines.append(f"# AMOEBA key file generated by Poltype2")
        lines.append(f"# Molecule: {mol.name}")
        lines.append(f"# Formula:  {mol.formula}")
        lines.append(f"# Atoms:    {mol.num_atoms}")
        lines.append("")

        # Parameter file reference
        lines.append(f"parameters  {config.prm_file_path}")
        lines.append("")

        # Atom definitions
        lines.append("# Atom definitions")
        rdmol = mol.rdmol
        for i in range(mol.num_atoms):
            atom = rdmol.GetAtomWithIdx(i)
            symbol = atom.GetSymbol()
            tinker_idx = i + 1
            atomic_num = atom.GetAtomicNum()
            mass = atom.GetMass()
            valence = atom.GetTotalDegree()
            # Use index-based type/class until real type assignment
            lines.append(
                f"atom  {tinker_idx:>5d}  {tinker_idx:>5d}  {symbol:<2s}"
                f'  "{mol.name} {symbol}{tinker_idx}"'
                f"  {atomic_num:>5d}  {mass:>10.3f}  {valence:>3d}"
            )
        lines.append("")

        # Optimisation energy (if available)
        opt_result = context.get_artifact("opt_result")
        if opt_result is not None:
            lines.append(
                f"# Optimised energy: {opt_result.energy:.6f} Hartree"
            )
            lines.append("")

        # Multipole frames placeholder (if available)
        multipole_frames = context.get_artifact("multipole_frames")
        if multipole_frames is not None:
            lines.append("# Multipole frames computed from ESP data")
            lines.append(
                f"# ESP grid points: {multipole_frames.get('esp_grid_points', 'N/A')}"
            )
            lines.append("")

        # Torsion scans placeholder (if available)
        torsion_scans = context.get_artifact("torsion_scans")
        if torsion_scans is not None and torsion_scans:
            lines.append(f"# Torsion scans: {len(torsion_scans)} bond(s)")
            for bond in torsion_scans:
                lines.append(f"#   bond {bond}")
            lines.append("")

        return lines
